// Next
import type { Metadata } from "next"
import { Inter } from "next/font/google"

// Third party
import { Toaster } from "sonner"

// Project
import "../styles/global.css"
import ReactQueryProvider from "@/utils/query"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Book wise",
  description: "Generated by create next app",
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        <link rel='icon' type='image/svg+xml' href='/icon.svg' />
      </head>

      <body className={inter.className}>
        <ReactQueryProvider>
          <Toaster richColors />

          <div className="h-full bg-gray-900 text-gray-100">
            {children}
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
